language: generic

branches:
  only:
    - master
    - develop
    - /^release-.*$/
    - /^v\.\d\.\d\.\d$/
    # NOT change the REGEX for v.#.#.# tags
    # If you change the REGEX, plz, update TravisTagTest with the REGEX, and keep tests passing

env:
  matrix:
    - COMPILE_METHOD=World
    - COMPILE_METHOD=Universe
    - COMPILE_METHOD=Barcelona
    - COMPILE_METHOD=Planet
    - COMPILE_METHOD=Schibsted

script: echo $COMPILE_METHOD
